### ISSUE TITLE
Not an issue, but...

### ISSUE THREAD

**Issue by Yorchbs** [shauleiz/SmartPropoPlus#5]
I would like to know what method SmartPropoPlus uses to read the PPM wave from the audio input of the microphone since I am trying to read ppm inputs also from the microphone but with Python and it would be based on how SmartPropoPlus reads it.
Thank you!

**Comment by shauleiz** [comment]
Not sure I understand. It just reads the audio buffer and analyzes the data. Do you need a pointer to the actual function?

**Comment by Yorchbs** [comment]
If you could, I would appreciate it a lot because in my program I have tried to read the values of the audio input (0 to 255) and convert them to high low to create the PPM wave but I can't get it to work so if I would appreciate knowing what is the function that Get the job done, yeah

**Comment by shauleiz** [comment]
### Preface:
First, I will have to confess that since I wrote the code passed about 10 years. So lets hope my memory still serves me.
I'm not sure where you have your problem (if any) so I have to be a little long:

In order to capture the audio (e.g. get the audio in a buffer) I used  [Core Audio APIs](https://docs.microsoft.com/en-us/windows/win32/coreaudio/core-audio-apis-in-windows-vista). You can see how I used them in file 
SmartPropoPlus/SPP4/branches/StateMachineStudies/SppAudio/SppAudio.cpp.

Then, I had to convert the stream of audio level values into **pulses**.  Then feed the pulses into a PPM decoder that converts the pulses into channel values. Note that this is all done online - with every pulse you get you pass it over for decoding and then wait for a new pulse. One other important note: SmartPropoPlus supports several decoders besides generic PPM. The correct decoder function is called by reference (a pointer to the function) - this might be a bit tricky to figure out.

### Description:
Function  CSppProcess::CaptureAudio(void) in file SmartPropoPlus/SPP4/branches/Spp/SppProcess/SppProcess.cpp 
Loops forever. With every loop it gets a new audio packet (GetAudioPacket()).
With every packet it calls function ProcessWave() that processes the audio data.

Function CSppProcess::ProcessWave(BYTE * pWavePacket, UINT32 packetLength)
Gets a buffer of audio data.
Converts it to pulses. A pulse have polarity and length.
For every pulse it detects it calls the decoding function which hides inside an array of decoders. It looks like this: m_ListProcessPulseFunc[m_iActiveProcessPulseFunc].func(PulseLength, negative);
But you just ignore it and pretend that it really calls function ProcessPulsePpm().

Function CSppProcess::ProcessPulsePpm(int width, BOOL input)
This is the decoder. It receives a pulse and updates the list of channels accordingly.
It is quite elaborated (e.g. it removes jitter) but finally it just write data to an array of channel position - m_Position[]

Hope this helped

**Comment by Yorchbs** [comment]
You are literally GOD, thanks to you I have understood everything I need, thanks for the time and the explanation!!!!
